import re
import os
import sys

root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
files = [
    os.path.join(root, 'css', 'bootstrap.min.css'),
    os.path.join(root, 'css', 'font-awesome.min.css'),
    os.path.join(root, 'css', 'style.css'),
    os.path.join(root, 'css', 'footer.css'),
]
out = os.path.join(root, 'css', 'bundle.min.css')
parts = []

for f in files:
    if not os.path.exists(f):
        print('ERROR: missing file', f)
        sys.exit(1)
    with open(f, 'r', encoding='utf-8') as fh:
        s = fh.read()
    # keep already-minified vendor css as-is; basic-minify project css
    base = os.path.basename(f).lower()
    if base.endswith('.min.css') or 'bootstrap' in base or 'font-awesome' in base:
        parts.append(s)
    else:
        # remove /* comments */
        s = re.sub(r'/\*.*?\*/', '', s, flags=re.S)
        # collapse whitespace
        s = re.sub(r'\s+', ' ', s)
        s = s.strip()
        parts.append(s)

with open(out, 'w', encoding='utf-8') as w:
    w.write('/* bundle.min.css - auto-generated by make_bundle.py */\n')
    for p in parts:
        w.write(p)
        w.write('\n')

print('WROTE', out)
